var fs=require("fs");
var taishotoc="/CBReader/toc/T*.toc";

var glob=require("glob");
var out=[];//,names=[],nos=[];
var processfile=function(fn) {
	var vol=fn.substr(fn.length-7,3); //file name might have a,b suffix
	if (vol[0]=="T") vol=vol.substr(1);
	if (vol[vol.length-1].match(/[a-z]/)) vol=vol.substr(0,vol.length-1);
	var arr=fs.readFileSync(fn,"ucs2").split(/\r?\n/g).map(function(L){
		var m=L.match(/<name>T(\d+[a-z]?) (.*?) \((\d+)卷\)</);
		if (m) {
			var name='"'+m[2]+'"';//names.push();
			var no='"T'+vol+'n'+m[1]+'"';//nos.push(); //so that it can link to http://tripitaka.cbeta.org/
			//out.push('{"n":"'+m[1]+',"name":"'+m[2]+'","juan":"'+m[3]+'"}')
			out.push("["+no+","+name+"]");
		}
	});
}
var processfiles=function(files) {
	files.map(processfile);
}
glob(taishotoc,function(err,data){
	processfiles(data.filter(function(f){return f.match(/T\d+/)}));
	var output="//generated by https://github.com/ksanaforge/cbeta2014/blob/master/extract_sutra_no_name.js\n"+
	"//Sutra No can be used URL parameter, e.g http://tripitaka.cbeta.org/T01n0001\n";
	//output+="var names=["+names.join(",\n")+"];\n"+
	//"var nos=["+nos.join(",\n")+"];\n"+
	output+="module.exports=["+out.join(",\n")+"]";
	fs.writeFileSync("taishonames.js",output,"utf8");
});
